Adicionando umas features bullet
Ballerini-Server/BalleBot pull request #10
Opened 2023-03-04 00:42 UTC by AlphaLawless

- Removido o `package-lock.json` do `.gitignore`.

- Dependências atualizadas:
```bash
 dotenv                           ^10.0.0  → ^16.0.3
 @commitlint/cli                  ^12.1.4  →  ^17.4.4
 @commitlint/config-conventional  ^12.1.4  →  ^17.4.4
 axios                            ^0.25.0  →   ^1.3.4
 commitizen                        ^1.0.4  →   ^4.3.0
 cz-conventional-changelog         ^3.0.1  →   ^3.3.0
 eslint                           ^7.28.0  →  ^8.35.0
 eslint-config-airbnb             ^18.2.1  →  ^19.0.4
 eslint-config-airbnb-base        ^14.2.1  →  ^15.0.0
 eslint-config-prettier            ^8.3.0  →   ^8.6.0
 eslint-plugin-import             ^2.23.4  →  ^2.27.5
 eslint-plugin-prettier            ^3.4.0  →   ^4.2.1
 husky                             ^6.0.0  →   ^8.0.3
 lint-staged                      ^11.0.0  →  ^13.1.2
 nodemon                          ^2.0.7  →  ^2.0.20
 prettier                         ^2.3.1  →   ^2.8.4
 ```
- Adicionado o docker para um melhor desenvolvimento e possívelmente a criação de clusters futuramente

2023-03-16 16:45 UTC, Matan18 requested changes
Gosto da ideia de transformar em Docker, mas não acho que todas as alterações fazem sentido (principalmente sobre variáveis de ambiente e formatação de código adicionadas).

2023-03-16 16:45 UTC, Matan18 commented on .env.example
> +prefix=
Pq vc trocou a variável para minúscula se na variável abaixo você trocou para maiúscula?

2023-03-16 16:45 UTC, Matan18 commented on src/commands/mods/management/unwarn.command.js
> +          message.member.roles.highest.position &&
Isso foi correção do ESLint? Me parece errado (a linha de cima e a linha de baixou não mudaram a identação)

2023-03-16 16:45 UTC, mateus-andriola commented on src/commands/padawan/management/mute.command.js
> +              message.member.roles.highest.position &&
Isso foi correção do ESLint? Me parece errado (a linha de cima e a linha de baixou não mudaram a identação)

2023-03-16 16:45 UTC, Matan18 commented on src/commands/padawan/management/warn.command.js
> +              message.member.roles.highest.position &&
Isso foi correção do ESLint? Me parece errado (a linha de cima e a linha de baixou não mudaram a identação)

2023-03-17 15:06 UTC, AlphaLawless commented on .env.example
> +prefix=
Essa parte eu não entendi o que você quis dizer com: "trocou para maiúscula", eu apenas segui o que estava dentro [src/events/guild/messageCreate.event.js](https://github.com/Ballerini-Server/BalleBot/blob/235ffdb407f695f1af3b9bd22e6fc2ef6f2af8c3/src/events/guild/messageCreate.event.js)

2023-03-17 15:06 UTC, AlphaLawless commented on src/commands/mods/management/unwarn.command.js
> +          message.member.roles.highest.position &&
Foi erro do meu lint, eu vou corrigir isso!

2023-03-18 02:03 UTC, AlphaLawless commented on .env.example
> +prefix=
Fix!

2023-03-18 02:04 UTC, AlphaLawless commented on src/commands/mods/management/unwarn.command.js
> +          message.member.roles.highest.position &&
Eu analisei esse problema de lint e isso está ocorrendo por conta do POSIX... porque na minha maquina não tem nenhuma configuração de eslint, e isso tudo é coisa que veio instalado e configurado do projeto.

2023-03-18 02:11 UTC, AlphaLawless commented on src/commands/mods/management/unwarn.command.js
> +          message.member.roles.highest.position &&
Essa imagem abaixo pode comprovar o que eu estou dizendo. O eslint+prettier configurado para esse projeto não deixa esse código tocar na *line numbers*.
![image](https://user-images.githubusercontent.com/65187737/226077637-8854bc40-4a8f-4ada-a0f7-0b5f432f223a.png)
OBS: Esse espaço que aparece no que está de verde é coisa do GitHub, no código ele não aparece.

2023-03-18 19:49 UTC, Matan18 approved these changes
LGTM

2023-03-29 19:13 UTC, tauz-hub approved these changes
revised, new dependencies really compatible, great job!

2023-03-29 19:14 UTC, merged